train:
  batch_size: 10
  epochs: 50
  learning_rate: 0.001
  num_workers: 4

data:
  main_path: "C:\\Users\\Itziar\\Documents\\Documentos\\TFG-INF-DATOS\\archive2"

model:
   model_name: "efficientnetb0" # mobilenetv2,efficientnetb0,yolo,resnet18,vitsmall,unetresnet34
   model_path: null
   num_classes : 2

save:
  output_dir: null
  results_path: null
  metrics_path: null
