train:
  batch_size: 16
  epochs: 40
  learning_rate: 0.001
  device: "cuda"
  num_workers: 4

data:
  main_path: "/content/drive/MyDrive/TFG/datos"

model:
   model_name: "mobilenetv2" # mobilenetv2,efficientnetb0,yolo,resnet18,vitsmall,unetresnet34
   model_path: null #donde se guarda el modelo
   num_classes : 2


